version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: bangkoo
      MONGO_INITDB_ROOT_USERNAME: bangkoo
      MONGO_INITDB_ROOT_PASSWORD: bangkoo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bangkoo-backend
    restart: always
    env_file:
      - .env
    ports:
      - "80:8080"               # 호스트 80 → 컨테이너 8080 매핑
    depends_on:
      - mongodb

volumes:
  mongo-data:
