spring:
  profiles:
    active: dev
  config:
    import:
      - "classpath:application-db.yml"
      - "optional:file:.env"  # .env 파일도 로드



server:
  port: 8080

ai:
  server:
    url: http://localhost:8000/api

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

jwt:
  algorithm: HS256
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-ms: 1800000 # 30분
  refresh-token-expiration-ms: 604800000 # 7일

security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: ${KAKAO_APP_CLIENT_ID:default}  # .env에서 가져옴
          client-secret: ${KAKAO_APP_CLIENT_SECRET}  # .env에서 가져옴
          client-authentication-method: client_secret_post
          authorization-grant-type: authorization_code
          redirect-uri: ${KAKAO_REDIRECT_URL}
          scope: profile_nickname,account_email
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id



  data:
    mongodb:
      uri: mongodb+srv://bangkoo:bangkoo@bangkoo.3bjilqn.mongodb.net/bangkoo?retryWrites=true&w=majority&appName=bangkoo



