name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev        # 또는 배포 트리거로 쓸 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Gradle
        run: ./gradlew clean bootJar

      - name: Zip artifact
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/app.jar
          echo "web: java -jar app.jar" > deploy/Procfile
          cd deploy
          zip -r ../deploy.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET }}/deploy.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="deploy.zip"
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label $GITHUB_SHA
